image: katalonstudio/katalon
services:
 - docker:dind

stages:
 - test

run_katalon_test_suite:
      stage: test
      tags:
        - docker
      script:
        - katalonc -noSplash -runMode=console -projectPath="." -retry=0 -testSuitePath="Test Suites/TestSuiteCI" -executionProfile="default" -browserType="Chrome (headless)" -apiKey="<Your API_KEY>"